- name: Demo on play Level varibles
  hosts: all
  vars:
    URL : har_play_com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}
# In ansible varibles will call by double flower braces


- name: Demo on task level varibles
  hosts: all
  tasks:
    - name: Print URL
      vars: 
        URL : "task_level_varible"
      ansible.builtin.debug:
        msg: "URL - {{ URL }}"

- name: load vars from a file
  hosts: all
  vars_files:
    - comman_vars.yml
  tasks:
    - name: Print vars from file
      ansible.builtin.debug:
        msg: "{{URL}}"

- name: role level varibles
  hosts: all
  vars:
    URL_PLY: "PLY_URL"
  roles:
    - sample
    - sample02

- name: shell module
  hosts: all
  tasks:
    - ansible.builtin.shell: uptime
      register: output_uptime
    - ansible.builtin.debug:
        msg: "{{output_uptime}}"

